set(sources
		src/WorldGenerator.cpp
		src/Tile.cpp
		src/Corner.cpp
		src/Edge.cpp
		src/Road.cpp
		src/Settlement.cpp
		src/Territory.cpp
		src/DiceRoller.cpp
		src/Sector.cpp
		src/Harbour.cpp
		src/TriggerEffectCollection.cpp
		src/TradingCenter.cpp
		src/Resource.cpp
		src/JsonUtil.cpp
		src/JsonUtil.h
		src/Game.cpp
)

set(exe_sources
		src/main.cpp
		${sources}
)

set(headers
		include/settlers/WorldGenerator.h
		include/settlers/Tile.h
		include/settlers/Corner.h
		include/settlers/Edge.h
		include/settlers/Road.h
		include/settlers/Settlement.h
		include/settlers/Territory.h
		include/settlers/Sector.h
		include/settlers/Harbour.h
		include/settlers/DiceRoller.h
		include/settlers/TriggerEffectCollection.h
		include/settlers/ITileObject.h
		include/settlers/ICornerObject.h
		include/settlers/IEdgeObject.h
		include/settlers/ISectorObject.h
		include/settlers/TradingCenter.h
		include/settlers/Resource.h
		include/settlers/Game.h
		include/settlers/IWorld.h
		include/settlers/IGameObserver.h
)

set(test_sources
		src/mock/MockWorld.h
		src/mock/MockGameObserver.h
)

set(test_exe_sources
		src/WorldGenerator_Tests.cpp
		src/Corner_Tests.cpp
		src/DiceRoller_Tests.cpp
		src/Tile_Tests.cpp
		src/TradingCenter_Tests.cpp
		src/Resource_Tests.cpp
		src/Game_Tests.cpp
		)
